- name: Mise à jour du système d'exploitation
  hosts: all
  serial: 1
  tasks:
    - name: Mise à jour du système d'exploitation
      ansible.builtin.include_role:
        name: os
        tasks_from: upgrade-now
